name: clip-faiss

channels:
  - nvidia/label/cuda-11.6.0
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cuda-toolkit=11.6.0
  - python=3.10.6
  - pip=22.3.0
  - scikit-image=0.19.3
  - matplotlib=3.6.0
  - imageio=2.22.0
  - typer=0.6.1
  - pytorch=1.12.1
  - torchvision=0.13.0
  - torchaudio=0.12.1
  - ftfy=6.1.1
  - regex=2022.9.13
  - tqdm=4.38.0
  - faiss-gpu=1.7.2
  - h5py=3.7.0
  - fastapi=0.85.1
  - uvicorn-standard=0.19.0
  - pip:
      - git+https://github.com/openai/CLIP.git
      - pydantic

variables:
  PYTHONNOUSERSITE: 1
